### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by messier95** [PierreMasselot/Frontier-FrenchScientificYoutube#2]
Hi Pierre!

Thanks a lot for sharing these files. The script for extracting the channel information saved me a lot of time during my current research of German science YouTubers. 

To create my sample, I also wanted to use the video information script. Unfortunately, it crashes when using it and does not write the "video_list_human_readable.csv" file. APIs were added into the script and the file "all_youtube_ids.txt" was created with one channel ID for testing. For the other script, both API and .txt file worked.

Sadly, as a communication researcher, I am not able to dig deep into the code. Did I miss something, or is the script no longer working? Maybe because YouTube changed the dislike statistics?

Thanks a lot for your time and expertise!

Cheers,
Manuel

**Comment by messier95** [comment]
Missed to install the pyexcel_ods module, now it works for me. Sorry for the trouble!

**Comment by PierreMasselot** [comment]
Dear Manuel,

Sorry not to have replied earlier.
Happy the issue seems to be sorted.

Pierre

**Comment by messier95** [comment]
Hello again Pierre, 

thanks for your reply. 

The mentioned issue was sorted, but after scraping around ~2000 Videos from 15 channels, I encountered the "urllib.error.HTTPError: HTTP Error 403: Forbidden" Error. 

I tried to resolve the issue by restricting the API to the YouTube Data API v3 and adding the following header information. Unfortunately, neither solved the error.

```python
...
site= 'https://www.googleapis.com/youtube/v3/searchpart=snippet&channelId='+channel_id+'&type=video&key='+api_key+'&maxResults=50&order=date'+next_page
hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
       'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'none',
       'Accept-Language': 'en-US,en;q=0.8',
       'Connection': 'keep-alive'}
req = Request(site, headers=hdr)
page = urlopen(req)
contents = page.read()
json_data = json.loads(contents)
...

```

My next step is to try to construct a service instance with my client.secret.json file. For now, I have not been able to successfully do that.

Are you familiar with this error? Do you know any workaround for it?

Thanks a lot in advance and have a great day!
Manuel

**Comment by stephanedebove** [comment]
Hi messier95,
I worked with Pierre on this project.
The first thing that comes to my mind is that you’ve hit your quota of daily requests. You’ll find this information in your google API account. If that’s the case you’ll have to query a little bit each day, or ask google to increase your quota (there’s a form for that I think in your account).

**Comment by messier95** [comment]
Hi Stephane,

thanks a lot for your reply and your help. You are completely right, I exceeded the limited quota, which led to the issue. Thanks also for the info on how to increase it, I just submitted the form.

Have a great day!
Manuel
